services:

  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ecommjava
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./basedata.sql:/docker-entrypoint-initdb.d/1-basedata.sql:ro

    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -proot --silent"
        ]

      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s


  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ecommerce-app

    depends_on:
      mysql:
        condition: service_healthy

    restart: unless-stopped

    ports:
      - "8082:8080"

    environment:
      DB_DRIVER: com.mysql.cj.jdbc.Driver

      DB_URL: jdbc:mysql://mysql:3306/ecommjava?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

      DB_USERNAME: root
      DB_PASSWORD: root

      HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
      HIBERNATE_SHOW_SQL: "true"
      HIBERNATE_HBM2DDL_AUTO: update

      ENTITYMANAGER_PACKAGES_TO_SCAN: com


volumes:
  mysql_data: