# JSP configuration
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

# Database
db.driver=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

db.url=${DB_URL:jdbc:mysql://mysql:3306/ecommjava?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

db.username=${DB_USERNAME:root}
db.password=${DB_PASSWORD:root}

# Hibernate
hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQL5Dialect}

hibernate.show_sql=${HIBERNATE_SHOW_SQL:true}

hibernate.hbm2ddl.auto=${HIBERNATE_HBM2DDL_AUTO:update}

entitymanager.packagesToScan=${ENTITYMANAGER_PACKAGES_TO_SCAN:com}

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true